import Config

# Track environment at runtime (for conditional behavior in workers, etc.)
config :pavoi, env: :prod

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :pavoi, PavoiWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Enable Oban cron jobs in production
config :pavoi, Oban,
  plugins: [
    {Oban.Plugins.Pruner, max_age: 60 * 60 * 24 * 7},
    {Oban.Plugins.Lifeline, rescue_after: :timer.seconds(60)},
    {Oban.Plugins.Cron,
     crontab: [
       # Sync products every 24 hours (at midnight UTC)
       {"0 0 * * *", Pavoi.Workers.ShopifySyncWorker},
       # Sync TikTok Shop products every 24 hours (at midnight UTC)
       {"0 0 * * *", Pavoi.Workers.TiktokSyncWorker},
       # Sync BigQuery orders to Creator CRM every 24 hours (at midnight UTC)
       {"0 0 * * *", Pavoi.Workers.BigQueryOrderSyncWorker},
       # Refresh TikTok access token every 30 minutes (prevents token expiration)
       {"*/30 * * * *", Pavoi.Workers.TiktokTokenRefreshWorker},
       # Monitor TikTok live status every 2 minutes
       {"*/2 * * * *", Pavoi.Workers.TiktokLiveMonitorWorker},
       # Enrich creator profiles from TikTok Marketplace API every 30 minutes
       # Small batches (75) complete quickly, avoiding rate limits
       # 48 runs/day × 75 = 3600 creators/day (with margin for rate limit pauses)
       {"*/30 * * * *", Pavoi.Workers.CreatorEnrichmentWorker}
     ]}
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
